name: linter

on: [push]

permissions:
  contents: read
  statuses: write

jobs:
  lint:
    name: project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run linter
        run: |
         docker run \
            -e RUN_LOCAL=true \
            -e DEFAULT_BRANCH=main \
            -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            -v ${{ github.workspace }}:/tmp/lint \
            -w /tmp/lint \
            ghcr.io/linter/linter:slim-v6.4.1

